apiVersion: v1
kind: Namespace
metadata:
  name: web-snippetbox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snippetbox-pod # Base POD name
  namespace: web-snippetbox
spec:
  selector:
    matchLabels:
      app: snippetbox # Selector for POD name search.
  template:
    metadata:
      labels:
        app: snippetbox
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
      # sales-api container configuration
      - name: snippetbox-api
        image: snippetbox-api-image
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: web-snippetbox
spec:
  type: ClusterIP
  selector:
    app: snippetbox
  ports:
  - name: snippetbox-api
    port: 4000
    targetPort: sales-api
